var countdownGenerator = function (x) {
  var count = x

  return function() {
    if (count > 0){
      console.log("T-minus " + count + "...");
      count -=1;

    } else if (count === 0) {
      console.log("Blast Off!");
      count -=1;
    } else {
      console.log("Rockets already gone, bub!")
    }
  }
};

var countdown = countdownGenerator(10);
countdown(); // T-minus 10...
countdown(); // T-minus 9...
countdown(); // T-minus 8...
countdown(); // T-minus 7...
countdown(); // T-minus 6...
countdown(); // T-minus 5...
countdown(); // T-minus 4...
countdown(); // T-minus 3...
countdown(); // T-minus 2...
countdown(); // T-minus 1...
countdown(); // Blast Off!
countdown(); // Rockets already gone, bub!
